/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSkillsDbRouteImport } from './routes/_layout.skills-db'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutHistoryRouteImport } from './routes/_layout.history'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout.analytics'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsDbRoute = LayoutSkillsDbRouteImport.update({
  id: '/skills-db',
  path: '/skills-db',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills-db': typeof LayoutSkillsDbRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof LayoutAnalyticsRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills-db': typeof LayoutSkillsDbRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills-db': typeof LayoutSkillsDbRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/history' | '/settings' | '/skills-db'
  fileRoutesByTo: FileRoutesByTo
  to: '/analytics' | '/history' | '/settings' | '/skills-db' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/analytics'
    | '/_layout/history'
    | '/_layout/settings'
    | '/_layout/skills-db'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills-db': {
      id: '/_layout/skills-db'
      path: '/skills-db'
      fullPath: '/skills-db'
      preLoaderRoute: typeof LayoutSkillsDbRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsDbRoute: typeof LayoutSkillsDbRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsDbRoute: LayoutSkillsDbRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
