/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafeguardsRouteImport } from './routes/safeguards'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout.analytics'
import { Route as LayoutCompareRouteImport } from './routes/_layout.compare'
import { Route as LayoutHistoryRouteImport } from './routes/_layout.history'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutSkillsDbRouteImport } from './routes/_layout.skills-db'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardsRoute = SafeguardsRouteImport.update({
  id: '/safeguards',
  path: '/safeguards',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompareRoute = LayoutCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsDbRoute = LayoutSkillsDbRouteImport.update({
  id: '/skills-db',
  path: '/skills-db',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/safeguards': typeof SafeguardsRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/compare': typeof LayoutCompareRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills-db': typeof LayoutSkillsDbRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/safeguards': typeof SafeguardsRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/compare': typeof LayoutCompareRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills-db': typeof LayoutSkillsDbRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/safeguards': typeof SafeguardsRoute
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/compare': typeof LayoutCompareRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills-db': typeof LayoutSkillsDbRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/methodology'
    | '/privacy'
    | '/safeguards'
    | '/analytics'
    | '/compare'
    | '/history'
    | '/settings'
    | '/skills-db'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/features'
    | '/methodology'
    | '/privacy'
    | '/safeguards'
    | '/analytics'
    | '/compare'
    | '/history'
    | '/settings'
    | '/skills-db'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/about'
    | '/features'
    | '/methodology'
    | '/privacy'
    | '/safeguards'
    | '/_layout/analytics'
    | '/_layout/compare'
    | '/_layout/history'
    | '/_layout/settings'
    | '/_layout/skills-db'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  SafeguardsRoute: typeof SafeguardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguards': {
      id: '/safeguards'
      path: '/safeguards'
      fullPath: '/safeguards'
      preLoaderRoute: typeof SafeguardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/compare': {
      id: '/_layout/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof LayoutCompareRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills-db': {
      id: '/_layout/skills-db'
      path: '/skills-db'
      fullPath: '/skills-db'
      preLoaderRoute: typeof LayoutSkillsDbRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutCompareRoute: typeof LayoutCompareRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsDbRoute: typeof LayoutSkillsDbRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutCompareRoute: LayoutCompareRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsDbRoute: LayoutSkillsDbRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  SafeguardsRoute: SafeguardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
